name: deploy-gh-pages
run-name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Deploy to GitHub Pages
        uses: borales/actions-yarn@v4
        with:
          cmd: run deploy


